#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

exchange-rates-current:
    path: /api/v1/exchange-rates/{date}
    controller: App\Controller\ExchangeRatesController::getList
    methods: [ GET ]
    requirements:
        date: \d{4}-\d{2}-\d{2}
    defaults:
        date: null

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

