# config/services.yaml
parameters:
    nbp_url: '%env(NBP_URL)%'

imports:
    - { resource: 'custom/currencies.yaml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/App/Controller/'
        autowire: true
        tags: ['controller.service_arguments']

    # Add factory service to create an HTTP client with base URL
    App\Factory\HttpClientFactory:
        arguments:
            $baseUri: '%nbp_url%'

    Symfony\Contracts\HttpClient\HttpClientInterface:
        factory: ['@App\Factory\HttpClientFactory', 'createHttpClient']

    # Define NationalBankService to use the HTTP client
    App\Services\NationalBankService:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $currencies: '%currencies%'

    App\Controller\ExchangeRatesController:
        arguments:
            $currencies: '%currencies%'
